/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RiskScores = IDL.Record({
  'cardiovascularRisk' : IDL.Text,
  'diabetesRisk' : IDL.Text,
  'obesityRisk' : IDL.Text,
  'hypertensionRisk' : IDL.Text,
});
export const PatientAssessment = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'activityLevel' : IDL.Text,
  'recommendations' : IDL.Text,
  'cholesterolLevel' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'systolicBP' : IDL.Nat,
  'bloodSugar' : IDL.Nat,
  'diastolicBP' : IDL.Nat,
  'gender' : IDL.Text,
  'smokingStatus' : IDL.Text,
  'timestamp' : Time,
  'familyHistory' : IDL.Text,
  'patientName' : IDL.Text,
  'riskScores' : RiskScores,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAssessment' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PatientAssessment)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAssessments' : IDL.Func([], [IDL.Vec(PatientAssessment)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitAssessment' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [PatientAssessment],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RiskScores = IDL.Record({
    'cardiovascularRisk' : IDL.Text,
    'diabetesRisk' : IDL.Text,
    'obesityRisk' : IDL.Text,
    'hypertensionRisk' : IDL.Text,
  });
  const PatientAssessment = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'activityLevel' : IDL.Text,
    'recommendations' : IDL.Text,
    'cholesterolLevel' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'systolicBP' : IDL.Nat,
    'bloodSugar' : IDL.Nat,
    'diastolicBP' : IDL.Nat,
    'gender' : IDL.Text,
    'smokingStatus' : IDL.Text,
    'timestamp' : Time,
    'familyHistory' : IDL.Text,
    'patientName' : IDL.Text,
    'riskScores' : RiskScores,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAssessment' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PatientAssessment)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAssessments' : IDL.Func([], [IDL.Vec(PatientAssessment)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitAssessment' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [PatientAssessment],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };