/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PatientAssessment {
  'id' : bigint,
  'age' : bigint,
  'bmi' : number,
  'activityLevel' : string,
  'recommendations' : string,
  'cholesterolLevel' : string,
  'submittedBy' : Principal,
  'systolicBP' : bigint,
  'bloodSugar' : bigint,
  'diastolicBP' : bigint,
  'gender' : string,
  'smokingStatus' : string,
  'timestamp' : Time,
  'familyHistory' : string,
  'patientName' : string,
  'riskScores' : RiskScores,
}
export interface RiskScores {
  'cardiovascularRisk' : string,
  'diabetesRisk' : string,
  'obesityRisk' : string,
  'hypertensionRisk' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAssessment' : ActorMethod<[bigint], [] | [PatientAssessment]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAssessments' : ActorMethod<[], Array<PatientAssessment>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitAssessment' : ActorMethod<
    [
      string,
      bigint,
      string,
      number,
      bigint,
      bigint,
      string,
      bigint,
      string,
      string,
      string,
    ],
    PatientAssessment
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];